### PR TITLE
clearFilters button

### PR DESCRIPTION
**Pull request by Alec8888**
Button that clears the filters and fetches donations

### CODE REVIEW

**Review by alyssaperkins — APPROVED** [review]
Looks good.

**Review by alyssaperkins — CHANGES_REQUESTED** [review]
There are merge conflicts, pull main into this branch and resolve all conflicts and then I will merge once resolved.

**Comment by Alec8888** [comment]
Resolved merge conflict.

**Comment by alyssaperkins** [comment]
Conflicts resolved. Approved for merge

**Pull request merged**
