### PR TITLE
Notification table update

### PR DESCRIPTION
**Pull request by gwatson90**
Notification table is updated when a reservation is made. Notification table was updated to provide some basic info about the notification. A banner was added on the account page to tell a user if they have notifications.

Notifications still need to be worked on for cancelled orders. 
Notifications

### CODE REVIEW

**Comment by Alec8888** [comment]
I do like the banner. With the banner notification I think it makes sense for the notifications section to be closed initially.

**Comment by gwatson90** [comment]
> I do like the banner. With the banner notification I think it makes sense for the notifications section to be closed initially.

Changed the notifications section to stay closed even if there are notifications.

**Comment by Alec8888** [comment]
accounts.vue  where you fetch notification

Here you can also get info from the corresponding donation. We should do this instead of adding the food column to Notifications.

.from('Notifications')
.select(notification_type, time, donations ( food ))

To display it do {{ message.donations.food }}

I think should just leave the email part out of the notification. Instead we can add text that appears on the donation cards that says something like "Reserved by: emailAddress". The donation card will have direct access to the needed email. Also, I think this make sense for the user, the notification just says you have a new reservation, then should see that reservation right below on the active pantry items.

**Comment by Alec8888** [comment]
pantry.vue where you create a new notification:

I think this should be insert instead of update. I noticed that I couldn't create more than two notifications; this may be why.

**Review by Alec8888 — APPROVED** [review]
Latest commit looks good. Approving

**Pull request merged**
