### PR TITLE
donation removed from pantry view when reservation confirmation clicked

### PR DESCRIPTION
**Pull request by Alec8888**
Fixed it so the donation is removed from the pantry after the reservation is made. Or should we simply route the user to the profile page instead?

### CODE REVIEW

**Comment by alyssaperkins** [comment]
I think it makes more sense to route the user to the profile page after a reservation has been reserved.  That way, they see that the active reserved donation is visible in their profile

**Comment by gwatson90** [comment]
> I think it makes more sense to route the user to the profile page after a reservation has been reserved. That way, they see that the active reserved donation is visible in their profile

I think that makes sense as well.

**Comment by Alec8888** [comment]
Updated to route to account page after reservation.

**Review by gwatson90 — APPROVED** [review]
Looks good to merge

**Pull request merged**
